volume_toco = (14*2.6*4.4)
carga_toco = 6000
trucktoco = (volume_toco > 160.16), (carga_toco < 6000)
print("A capacidade maxima do Truck toco e de:", carga_toco, ", com um volume de:", volume_toco)

volume_pacote = float(input("Entre com o volume do pacote em metros:"))
peso_pacote = float(input("Entre como peso do pacote em kg:"))
pacote = (volume_pacote, peso_pacote)
capacidade_rest  =(volume_toco - volume_pacote, carga_toco - peso_pacote)
volume_rest = (((volume_toco-volume_pacote)*100)/volume_toco)
carga_rest = (((carga_toco-peso_pacote)*100)/carga_toco)
perc_volume = ((volume_pacote*100)/volume_toco)
perc_peso = ((peso_pacote*100)/carga_toco)
print("Anda restam ",volume_rest,"% de area util","e",carga_rest,"% de capacidade de carga")
print("O pacote equivale a ",perc_volume,"% da capacidade volumetrica","e",perc_peso,"% da capacidade de carga")